// File generated by FlutterFire CLI.
// This file should be configured with your Firebase project settings.
// Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYBYKfLMecTh22k6Zm2K28uB9lKb75L2E',
    appId: '1:522536651284:android:70c783c35642028ee8f501',
    messagingSenderId: '522536651284',
    projectId: 'dish-flow-fb7b4',
    storageBucket: 'dish-flow-fb7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg5tBzFQ4zQ98kwHTyl50wXbXs1XVE5-E',
    appId: '1:522536651284:ios:681b965edd039c34e8f501',
    messagingSenderId: '522536651284',
    projectId: 'dish-flow-fb7b4',
    storageBucket: 'dish-flow-fb7b4.firebasestorage.app',
    iosBundleId: 'com.dishflow.app',
  );
}

